import ProfileComment from './Profile-comment.png';
const dataComment = [
            {
                "idC" : "1",
                "user": "9hdw ",
                "avatar": ProfileComment,
                "comment_date": "2d",
                "comment_body": "hahahah ",
                "up_votes": 120,
                "down_votes": 10,

            },
            {
                "idC" : "2",
                "user": "khif",
                "avatar": ProfileComment,
                "comment_date": "15h",
                "comment_body": "why not",
                "up_votes": 2,
                "down_votes": 13,
            },
            {
                "idC" : "3",
                "user": "9hdw ",
                "avatar": ProfileComment,
                "comment_date": "18h",
                "comment_body": "hahahah ",
                "up_votes": 120,
                "down_votes": 10,
            },
            {
                "idC" : "4",
                "user": "atti18",
                "avatar": ProfileComment,
                "comment_date": "1h",
                "comment_body": "Laugh track starts",
                "up_votes": 22,
                "down_votes": 19,
            },
            {
                "idC" : "5",
                "user": "takedahiromitsu",
                "avatar": ProfileComment,
                "comment_date": "23h",
                "comment_body": "Someone asked for a rumble?",
                "up_votes": 38,
                "down_votes": 2,
            },
            {
                "idC" : "6",
                "user": "note",
                "avatar": ProfileComment,
                "comment_date": "5h",
                "comment_body": "ok  ",
                "up_votes": 20,
                "down_votes": 39,   
            },
            {
                "idC" : "7",
                "user": "uskwm",
                "avatar": ProfileComment,
                "comment_date": "9h",
                "comment_body": "noooooo",
                "up_votes": 22,
                "down_votes": 133,
            },
            {
                "idC" : "8",
                "user": "art",
                "avatar": ProfileComment,
                "comment_date": "4h",
                "comment_body": "sure for now",
                "up_votes": 42,
                "down_votes": 39,
            },
            {
                "idC" : "9",
                "user": "ahmed",
                "avatar": ProfileComment,
                "comment_date": "2h",
                "comment_body": "Someone asked about this?",
                "up_votes": 28,
                "down_votes": 4,
            },
            {
                "idC" : "10",
                "user": "Awsatt",
                "avatar": ProfileComment,
                "comment_date": "13h",
                "comment_body": "It'd be good without that edit.",
                "up_votes": 43,
                "down_votes": 10,
            }
        ]

export default dataComment;